#!/bin/zsh
# -> Mac M1
#!/usr/bin/bash
# -> Basic Linux

sudo mongodump --forceTableScan --db research --collection articles -o /home/sozin/bin/mongobackup
echo wonderwall | scp -r research/ hark@192.168.1.166:/home/hark/bin/docker